# Generated by Django 5.2.17 on 2026-08-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('departamento', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cnh', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('van', 'Van')], max_length=10)),
                ('capacidade', models.PositiveIntegerField(help_text='Número total de ocupantes (incluindo motorista)')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('num_passageiros', models.PositiveIntegerField()),
                ('motivo', models.TextField()),
                ('protocolo', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='confirmada', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.colaborador')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.veiculo')),
            ],
        ),
    ]
